// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAty7f7tBJ29SmYma_NonHNXm70u2Z2MUg',
    appId: '1:520041215797:web:7274a80bdfd14ebebdbe7c',
    messagingSenderId: '520041215797',
    projectId: 'fluttercardgames',
    authDomain: 'fluttercardgames.firebaseapp.com',
    storageBucket: 'fluttercardgames.firebasestorage.app',
    measurementId: 'G-BLT6E2TY5T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlwxqyZEGVCroeeFkBU3Y8eoYF6Ot28l4',
    appId: '1:520041215797:android:e07d1709f66d6d55bdbe7c',
    messagingSenderId: '520041215797',
    projectId: 'fluttercardgames',
    storageBucket: 'fluttercardgames.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJI1rP4SGgj2QreIDyKpOQzdbXpkbl2VU',
    appId: '1:520041215797:ios:45137a211f6e66a1bdbe7c',
    messagingSenderId: '520041215797',
    projectId: 'fluttercardgames',
    storageBucket: 'fluttercardgames.firebasestorage.app',
    iosBundleId: 'com.example.flutterCardGames',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJI1rP4SGgj2QreIDyKpOQzdbXpkbl2VU',
    appId: '1:520041215797:ios:45137a211f6e66a1bdbe7c',
    messagingSenderId: '520041215797',
    projectId: 'fluttercardgames',
    storageBucket: 'fluttercardgames.firebasestorage.app',
    iosBundleId: 'com.example.flutterCardGames',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAty7f7tBJ29SmYma_NonHNXm70u2Z2MUg',
    appId: '1:520041215797:web:5adb665fb0730bc7bdbe7c',
    messagingSenderId: '520041215797',
    projectId: 'fluttercardgames',
    authDomain: 'fluttercardgames.firebaseapp.com',
    storageBucket: 'fluttercardgames.firebasestorage.app',
    measurementId: 'G-G2LLPG2B9S',
  );
}
